package(default_visibility=["//visibility:public"])
load("//rules:verilog.bzl", "verilog_library",
                            "verilog_test",
)

# Tests for instructions which use the ALU

verilog_test(
    name = "ora_imm_test",
    srcs = [ "ora_imm_test.v" ],
    deps = [ "//cpu6502" ],
)
verilog_test(
    name = "ora_zp_test",
    srcs = [ "ora_zp_test.v" ],
    deps = [ "//cpu6502" ],
)
verilog_test(
    name = "ora_zpx_test",
    srcs = [ "ora_zpx_test.v" ],
    deps = [ "//cpu6502" ],
)
verilog_test(
    name = "ora_abs_test",
    srcs = [ "ora_abs_test.v" ],
    deps = [ "//cpu6502" ],
)
verilog_test(
    name = "ora_absx_test",
    srcs = [ "ora_absx_test.v" ],
    deps = [ "//cpu6502" ],
)
verilog_test(
    name = "ora_absy_test",
    srcs = [ "ora_absy_test.v" ],
    deps = [ "//cpu6502" ],
)
verilog_test(
    name = "ora_ix_test",
    srcs = [ "ora_ix_test.v" ],
    deps = [ "//cpu6502" ],
)
verilog_test(
    name = "ora_iy_test",
    srcs = [ "ora_iy_test.v" ],
    deps = [ "//cpu6502" ],
)








