package(default_visibility=["//visibility:public"])
load("//rules:verilog.bzl",
     "verilog_library",
     "verilog_test")

verilog_library(
    name = "uart",
    srcs = [
        "uart.v",
    ],
)
